/**
 * Structured edits against a SlideML deck.
 *
 * Why: agent multi-turn workflows ("now make slide 3 punchier") would
 * otherwise require re-emitting the full YAML on every iteration. With
 * `editDeck` the agent (or human) can apply a small JSON ops list to the
 * sidecar source produced by a previous render and immediately recompile.
 *
 * Caveat: round-trips strip YAML comments and reformat. The sidecar is
 * auto-generated by `compile()` so this is acceptable for the agent flow;
 * if we later want comment-preserving edits we'll switch to `eemeli/yaml`'s
 * Document API.
 */

import { readFile } from "node:fs/promises";
import yaml from "js-yaml";
import { compile, type CompileOptions, type CompileResult } from "./index.js";

/** Discriminated union of edit operations. Paths use dot-bracket notation. */
export type EditOp =
  | { kind: "set"; path: string; value: unknown }
  | { kind: "delete"; path: string }
  | { kind: "insertSlide"; at: number; slide: Record<string, unknown> }
  | { kind: "deleteSlide"; at: number }
  | { kind: "moveSlide"; from: number; to: number };

export interface EditResult extends CompileResult {
  /** YAML body after applying all ops (also written to the sidecar). */
  yaml: string;
  /** Number of ops applied. */
  applied: number;
}

/**
 * Load a sidecar (or any SlideML YAML), apply structured ops, recompile.
 *
 * Compile options behave the same as `compile()` — pass `output` to also
 * write the .pptx and an updated sidecar.
 */
export async function editDeck(
  sidecarPath: string,
  ops: readonly EditOp[],
  opts: CompileOptions,
): Promise<EditResult> {
  const yamlBody = await readFile(sidecarPath, "utf8");
  const doc = yaml.load(yamlBody) as Record<string, unknown>;
  if (typeof doc !== "object" || doc === null) {
    throw new Error(`editDeck: sidecar at ${sidecarPath} is not a YAML mapping.`);
  }

  for (const op of ops) applyOp(doc, op);

  const newYaml = yaml.dump(doc, { lineWidth: 100, noRefs: true });
  const compiled = await compile(newYaml, opts);
  return { ...compiled, yaml: newYaml, applied: ops.length };
}

// ---------------------------------------------------------------------------
// Op application
// ---------------------------------------------------------------------------

function applyOp(doc: Record<string, unknown>, op: EditOp): void {
  switch (op.kind) {
    case "set":          return setPath(doc, op.path, op.value);
    case "delete":       return deletePath(doc, op.path);
    case "insertSlide":  return insertSlide(doc, op.at, op.slide);
    case "deleteSlide":  return deleteSlide(doc, op.at);
    case "moveSlide":    return moveSlide(doc, op.from, op.to);
  }
}

function insertSlide(doc: Record<string, unknown>, at: number, slide: Record<string, unknown>): void {
  const slides = ensureSlidesArray(doc);
  const idx = clampInsertIndex(at, slides.length);
  slides.splice(idx, 0, slide);
}

function deleteSlide(doc: Record<string, unknown>, at: number): void {
  const slides = ensureSlidesArray(doc);
  if (at < 0 || at >= slides.length) {
    throw new Error(`deleteSlide: index ${at} out of range (0..${slides.length - 1}).`);
  }
  slides.splice(at, 1);
}

function moveSlide(doc: Record<string, unknown>, from: number, to: number): void {
  const slides = ensureSlidesArray(doc);
  if (from < 0 || from >= slides.length) {
    throw new Error(`moveSlide: from=${from} out of range (0..${slides.length - 1}).`);
  }
  const [item] = slides.splice(from, 1);
  const dest = clampInsertIndex(to, slides.length);
  slides.splice(dest, 0, item);
}

function ensureSlidesArray(doc: Record<string, unknown>): unknown[] {
  const slides = doc["slides"];
  if (!Array.isArray(slides)) {
    throw new Error(`editDeck: top-level "slides" array is missing or not an array.`);
  }
  return slides;
}

function clampInsertIndex(at: number, length: number): number {
  if (at < 0) return 0;
  if (at > length) return length;
  return at;
}

// ---------------------------------------------------------------------------
// Path resolution — dot-bracket notation
//
//   "deck.header.left"
//   "slides[3].slots.title"
//   "slides[0].slots.items[2]"
//   "slides[3].notes"
// ---------------------------------------------------------------------------

interface PathStep { kind: "key"; key: string }

interface IndexStep { kind: "index"; index: number }

type Step = PathStep | IndexStep;

function parsePath(path: string): Step[] {
  const out: Step[] = [];
  // Tokenize: identifiers (letters/digits/underscore/dash), dots, brackets.
  const re = /([A-Za-z_][A-Za-z0-9_\-]*)|\[(\d+)\]/g;
  let m: RegExpExecArray | null;
  let consumed = 0;
  while ((m = re.exec(path)) !== null) {
    if (m.index !== consumed) {
      // Allow dots between tokens; anything else is illegal.
      const between = path.slice(consumed, m.index);
      if (!/^\.+$/.test(between)) {
        throw new Error(`editDeck: cannot parse path segment near "${between}" in "${path}".`);
      }
    }
    if (m[1] !== undefined) out.push({ kind: "key", key: m[1] });
    else if (m[2] !== undefined) out.push({ kind: "index", index: Number(m[2]) });
    consumed = re.lastIndex;
  }
  if (consumed !== path.length) {
    throw new Error(`editDeck: trailing junk in path "${path}" at position ${consumed}.`);
  }
  if (out.length === 0) throw new Error(`editDeck: empty path.`);
  return out;
}

function setPath(doc: unknown, path: string, value: unknown): void {
  const steps = parsePath(path);
  let cursor: unknown = doc;
  for (let i = 0; i < steps.length - 1; i++) {
    const step = steps[i]!;
    cursor = descendCreating(cursor, step, steps[i + 1]!);
  }
  const last = steps[steps.length - 1]!;
  if (last.kind === "key") {
    if (typeof cursor !== "object" || cursor === null || Array.isArray(cursor)) {
      throw new Error(`editDeck: cannot set "${last.key}" — parent is not an object (path "${path}").`);
    }
    (cursor as Record<string, unknown>)[last.key] = value;
  } else {
    if (!Array.isArray(cursor)) {
      throw new Error(`editDeck: cannot set [${last.index}] — parent is not an array (path "${path}").`);
    }
    cursor[last.index] = value;
  }
}

function deletePath(doc: unknown, path: string): void {
  const steps = parsePath(path);
  let cursor: unknown = doc;
  for (let i = 0; i < steps.length - 1; i++) {
    cursor = descend(cursor, steps[i]!);
    if (cursor === undefined) return; // path doesn't exist — no-op
  }
  const last = steps[steps.length - 1]!;
  if (last.kind === "key" && typeof cursor === "object" && cursor !== null && !Array.isArray(cursor)) {
    delete (cursor as Record<string, unknown>)[last.key];
  } else if (last.kind === "index" && Array.isArray(cursor)) {
    cursor.splice(last.index, 1);
  }
}

function descend(v: unknown, step: Step): unknown {
  if (step.kind === "key") {
    if (typeof v !== "object" || v === null || Array.isArray(v)) return undefined;
    return (v as Record<string, unknown>)[step.key];
  }
  return Array.isArray(v) ? v[step.index] : undefined;
}

function descendCreating(v: unknown, step: Step, next: Step): unknown {
  // Look up; if missing, create the right shape based on the NEXT step.
  if (step.kind === "key") {
    if (typeof v !== "object" || v === null || Array.isArray(v)) {
      throw new Error(`editDeck: cannot descend into "${step.key}" — parent is not an object.`);
    }
    const obj = v as Record<string, unknown>;
    if (obj[step.key] === undefined) {
      obj[step.key] = next.kind === "index" ? [] : {};
    }
    return obj[step.key];
  }
  if (!Array.isArray(v)) {
    throw new Error(`editDeck: cannot descend into [${step.index}] — parent is not an array.`);
  }
  if (v[step.index] === undefined) {
    v[step.index] = next.kind === "index" ? [] : {};
  }
  return v[step.index];
}
