export const RENDER_DIAGNOSTIC_CODES = [
  "OVERFLOW",
  "DROP",
  "COLLISION",
  "STRUCTURAL_OVERLAP",
  "SIBLING_INK_OVERLAP",
  "OVERLAY_OCCLUDES_FLOW",
  "DECORATIVE_OVERLAP",
  "EDGE_CLIPPED",
  "OFF_SLIDE",
  "TIGHT_GAP",
  "UNKNOWN_COLOR",
  "UNKNOWN_STYLE",
  "TINY_RECT",
  "SQUASHED",
  "TRUNCATED",
  "DEMOTED",
  "FALLBACK_FAILED",
  "FEATURE_CARD_OVER_CAPACITY",
  "CODE_BLOCK_OVERFLOW",
  "TITLE_OCCLUDED",
  "PIE_LABELS_HIDDEN",
  "EMPTY_CHART_DATA",
  "EMPTY_TABLE_DATA",
  "EVIDENCE_REGION_TOO_SMALL",
  "IMAGE_ASPECT_MISMATCH",
  "PROCESS_FLOW_OVER_CAPACITY",
  "TIMELINE_OVER_CAPACITY",
  "KPI_REGION_OVER_CAPACITY",
  "EQUATION_TOO_DENSE",
  "DONUT_SUMMARY_OVER_CAPACITY",
  "PAGE_OVER_CAPACITY",
  "REGION_OVER_CAPACITY",
  "ORG_OVERFLOW",
  "LOW_CONTRAST",
  "LOW_CONTRAST_FIXED",
  "SHAPE_INVISIBLE",
  "SHAPE_INVISIBLE_FIXED",
  "MISSING_ANCHOR_TARGET",
  "MISSING_DATA_BINDING_SOURCE",
] as const;

export type RenderDiagnosticCode = typeof RENDER_DIAGNOSTIC_CODES[number];

export const SOURCE_VALIDATION_CODES = [
  "INVALID_SLIDE_TRANSITION",
  "NODE_OUT_OF_BOUNDS",
  "TEXT_BOX_TOO_SHORT",
  "BACKGROUND_IMAGE_PARTIAL_HEIGHT",
  "TOP_LEVEL_LAYOUT_OVERLAP",
] as const;

export type SourceValidationCode = typeof SOURCE_VALIDATION_CODES[number];

export const SOURCE_VALIDATION_CODE: { readonly [K in SourceValidationCode]: K } = {
  INVALID_SLIDE_TRANSITION: "INVALID_SLIDE_TRANSITION",
  NODE_OUT_OF_BOUNDS: "NODE_OUT_OF_BOUNDS",
  TEXT_BOX_TOO_SHORT: "TEXT_BOX_TOO_SHORT",
  BACKGROUND_IMAGE_PARTIAL_HEIGHT: "BACKGROUND_IMAGE_PARTIAL_HEIGHT",
  TOP_LEVEL_LAYOUT_OVERLAP: "TOP_LEVEL_LAYOUT_OVERLAP",
} as const;

export const BLOCKING_RENDER_DIAGNOSTIC_CODES: ReadonlySet<string> = new Set([
  "FALLBACK_FAILED",
  "FEATURE_CARD_OVER_CAPACITY",
  "CODE_BLOCK_OVERFLOW",
  "COLLISION",
  "STRUCTURAL_OVERLAP",
  "SIBLING_INK_OVERLAP",
  "OVERLAY_OCCLUDES_FLOW",
  "TITLE_OCCLUDED",
  "EMPTY_CHART_DATA",
  "EMPTY_TABLE_DATA",
  "TINY_RECT",
  "LOW_CONTRAST",
  "SHAPE_INVISIBLE",
  "UNKNOWN_COLOR",
  "UNKNOWN_STYLE",
  "OFF_SLIDE",
  "MISSING_ANCHOR_TARGET",
  "MISSING_DATA_BINDING_SOURCE",
]);

export const QUALITY_RENDER_DIAGNOSTIC_CODES: ReadonlySet<string> = new Set([
  "TRUNCATED",
  "OVERFLOW",
  "DROP",
  "DEMOTED",
  "COLLISION",
  "STRUCTURAL_OVERLAP",
  "SIBLING_INK_OVERLAP",
  "OVERLAY_OCCLUDES_FLOW",
  "TINY_RECT",
  "FALLBACK_FAILED",
  "FEATURE_CARD_OVER_CAPACITY",
  "CODE_BLOCK_OVERFLOW",
  "LOW_CONTRAST_FIXED",
  "SHAPE_INVISIBLE_FIXED",
  "DECORATIVE_OVERLAP",
  "EDGE_CLIPPED",
  "TIGHT_GAP",
  "SQUASHED",
  "PIE_LABELS_HIDDEN",
  "EVIDENCE_REGION_TOO_SMALL",
  "IMAGE_ASPECT_MISMATCH",
  "PROCESS_FLOW_OVER_CAPACITY",
  "TIMELINE_OVER_CAPACITY",
  "KPI_REGION_OVER_CAPACITY",
  "EQUATION_TOO_DENSE",
  "DONUT_SUMMARY_OVER_CAPACITY",
  "PAGE_OVER_CAPACITY",
  "REGION_OVER_CAPACITY",
  "ORG_OVERFLOW",
]);

export function isBlockingRenderDiagnostic(code: unknown, severity?: unknown): boolean {
  if (severity === "error") return true;
  if (severity === "warn" || severity === "warning" || severity === "info") return false;
  return typeof code === "string" && BLOCKING_RENDER_DIAGNOSTIC_CODES.has(code);
}

export function isQualityRenderDiagnostic(code: unknown): boolean {
  return typeof code === "string" && QUALITY_RENDER_DIAGNOSTIC_CODES.has(code);
}
